---
plugin:
  id: "limma"
  name: "Limma Differential Expression"
  description: "Linear models for differential expression analysis using limma"
  version: "1.0.0"
  author: "CauldronGO Team"
  category: "analysis"
  icon: "difference"
  repository: "https://github.com/noatgnu/limma-plugin"

runtime:
  environments: ["r"]
  entrypoint: "limma.R"

inputs:
  - name: "input_file"
    label: "Input Data File"
    type: "file"
    required: true
    accept: ".csv,.tsv,.txt"
    description: "Proteomics or expression data file"

  - name: "annotation_file"
    label: "Annotation File"
    type: "file"
    required: true
    accept: ".csv,.tsv,.txt"
    description: "Sample annotation file with conditions"

  - name: "index_col"
    label: "Index Column"
    type: "text"
    required: false
    description: "Column name to use as feature identifier"

  - name: "log2"
    label: "Apply Log2 Transformation"
    type: "boolean"
    default: false
    description: "Apply log2 transformation before analysis"

  - name: "comparisons"
    label: "Comparisons"
    type: "file"
    required: false
    accept: ".csv,.tsv,.txt"
    description: "Comparison groups for differential analysis"

  - name: "impute_order"
    label: "Imputation Order"
    type: "select"
    required: false
    default: "before"
    options:
      - "before"
      - "after"
    description: "When to perform imputation relative to normalization (before or after normalization)"

  - name: "impute"
    label: "Imputation Method"
    type: "select"
    required: false
    default: "none"
    options:
      - "none"
      - "knn"
      - "MinDet"
      - "MinProb"
      - "min"
      - "zero"
      - "mixed"
      - "nbavg"
      - "with"
      - "QRILC"
      - "MLE"
      - "bpca"
    description: "Imputation method for missing values (select 'none' to skip imputation)"

  - name: "normalize"
    label: "Normalization Method"
    type: "select"
    required: false
    default: "none"
    options:
      - "none"
      - "quantiles"
      - "quantiles.robust"
      - "vsn"
      - "center.median"
      - "center.mean"
    description: "Normalization method to apply (select 'none' to skip normalization)"

  - name: "aggregate_column"
    label: "Aggregate By Column"
    type: "text"
    required: false
    description: "Column name to aggregate features (e.g., aggregate peptides to proteins). Leave empty to skip aggregation."

  - name: "aggregate_method"
    label: "Aggregation Method"
    type: "text"
    required: false
    default: "MsCoreUtils::robustSummary"
    description: "Method to use for feature aggregation (e.g., MsCoreUtils::robustSummary, median, mean)"

outputs:
  - name: "differential_results"
    path: "differential_analysis.txt"
    type: "data"
    description: "Differential expression analysis results"
    format: "tsv"

  - name: "contrast_matrix_info"
    path: "contrast_matrix_info.txt"
    type: "data"
    description: "Contrast matrix information showing comparison directions"
    format: "tsv"

execution:
  argsMapping:
    input_file: "--input_file"
    annotation_file: "--annotation_file"
    index_col: "--index_col"
    log2:
      flag: "--log2"
      when: "true"
    comparisons: "--comparison_file"
    impute: "--impute"
    impute_order: "--impute_order"
    normalize: "--normalize"
    aggregate_column: "--aggregate_column"
    aggregate_method: "--aggregate_method"

  outputDir: "--output_folder"

  requirements:
    r: ">=4.0"
    rPackagesFile: "r-packages.txt"

example:
  enabled: true
  values:
    input_file: "diann/imputed.data.txt"
    annotation_file: "differential_analysis/annotation.txt"
    comparisons: "differential_analysis/comparison.bca.txt"
    index_col: "Protein.Ids"
    log2: true
